### ISSUE TITLE
Question about balanced sampling

### ISSUE THREAD

**Issue by nhnhnh** [HensoldtOptronicsCV/MultispectralPedestrianDetection#7]
Thanks for your great work!
I wonder the details about _"the balanced sampling of images with and without pedestrains "_ mentioned in your paper's section 4.
Would you kindly describe it more? Or give some code or paper reference about it. 
THX :)

**Comment by Alx-Wo** [comment]
Dear nhnhnh,

It is actually fairly simple: For every batch we make sure, that the batch contains the same amount of images with pedestrians and without them. For example for batchsize 16, we sample 8 images from KAIST that contain pedestrians and 8 images from KAIST that do not contain pedestrians, according to the GT annotations.

Best regards,

**Comment by nhnhnh** [comment]
Thanks for your response!
